FROM p7hb/docker-spark:latest
RUN apt-get update && apt-get install python3 python3-pip -y
RUN pip3 install psycopg2 py-dateutil requests
RUN wget https://jdbc.postgresql.org/download/postgresql-42.2.1.jar --directory-prefix=/resources/
